<button id="send_test_message_button" class="button" type="button">
    <span id="send_test_message_text"><?= ('Send Test Message') ?></span>
</button>

<script>
    require([
        'jquery', 
        'mage/url', 
        'Magento_Ui/js/modal/alert' // Include the loader module
    ], function ($, urlBuilder, alert, loader) {
        $(document).ready(function() {
            $('#send_test_message_button').on('click', function (e) {
                e.preventDefault(); // Prevent any default behavior like form submission

                var ajaxUrl = '<?=(string) $block->getAjaxUrl(); ?>'; // URL for the AJAX request
                var formKey = window.FORM_KEY; // Get the form key from Magento's global JS variable
                var toNumber = $("#novel_notification_whatsapp_test_to").val();

                var spanText = $('#send_test_message_text');

                // Show the loader GIF
                spanText.html('<img src="<?=(string) $block->getViewFileUrl('mui/images/ajax-loader.gif'); ?>" alt="Loading..." />');

                $.ajax({
                    url: ajaxUrl,
                    type: 'POST',
                    data: {
                        form_key: formKey,
                        to: toNumber 
                    }, // Include the form key in the request
                    dataType: 'json',
                    success: function (response) {
                        if (response.success) {
                            alert({
                                title: 'Success',
                                content: response.message,
                                actions: { always: function() {} }
                            });
                        } else {
                            alert({
                                title: 'Error',
                                content: response.message,
                                actions: { always: function() {} }
                            });
                        }
                        spanText.html('<?=('Send Test Message') ?>');
                    },
                    error: function () {
                        // Revert span text back to original
                        alert({
                            title: 'Error',
                            content: 'An error occurred while sending the test message.',
                            actions: { always: function() {} }
                        });
                    }
                });
            });
        });
    });
</script>
