<?php
/**
 * @category   Novel
 * @package    Novel_CustomGrid
 * @author     akshaya11096@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Novel\CustomGrid\Model\ResourceModel\CustomGrid;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'customgrid_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'Novel\CustomGrid\Model\CustomGrid',
            'Novel\CustomGrid\Model\ResourceModel\CustomGrid'
        );
    }
}