<?php
/**
 * @category   Novel
 * @package    Novel_CustomGrid
 * @author     akshaya11096@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Novel\CustomGrid\Model\ResourceModel;

class CustomGrid extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('novel_customgrid', 'customgrid_id');   //here "novel_customgrid" is table name and "customgrid_id" is the primary key of custom table
    }
}